#!/usr/bin/env bash
# Displays the PID along with the process name, of 
#+ processes whose name contains the word "bash".
# shellcheck disable=SC2009
ps aux | grep bash | grep -v grep | awk '{print $2, $11}'
