#!/usr/bin/env bash
# Bahs script that dislays FizzBuzz when number is a multiple of 3 and 5, Fizz when number is multiple of 3, Buzz when number is multiple of 5, and number otherwise
for i in {1..100}
do
    if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]; then
    echo "FizzBuzz"
    elif [ $((i % 3)) -eq 0 ]; then
    echo "Fizz"
    elif [ $((i % 5)) -eq 0 ]; then
    echo "Buzz"
    else
    echo $i
    fi
done
