#!/usr/bin/env bash
# This script is displaying 4 and then "bad luck from chine", 9 then "bad luck from japan" and 17 then "bad luck from italy"
i=1
while [ $i -le 20 ]
do
    if [ $i -eq 4 ]
    then
        echo "$i"
        echo "bad luck from China"
    elif [ $i -eq 9 ]
    then
        echo "$i"
        echo "bad luck from Japan"
    elif [ $i -eq 17 ]
    then
        echo "$i"
        echo "bad luck from Italy"
    else
        echo "$i"
    fi
    i=$(( $i + 1 ))
done
