#!/usr/bin/env bash
# Connects to server 18.204.10.161 with key in ~/.ssh/school

# Define the server hostname or IP address
server=18.204.10.161

# Use SSH with the private key and the user 'ubuntu'
ssh -i ~/.ssh/id_rsa ubuntu@$server
